from Helper import Helper
from SymmetricCipher import Cipher
from view import Window



def cv2():
    zasifrovany_text = "LTTLQJHMHJSDSNUTRTHNZENAFYJQZRXPTSYWTQTZEIFOJOJONHMMJXQTOJXYJXYFQJGJEUJHSJKNWRFUWTYTUWNUWFANQFXUJHNFQSNITUQSJPITUWTMQNEJHJHMWTRJYJSUTPFEIJPIDEEFIFYJSJPIJSFNSYJWSJYZMJXQTEPTSYWTQZOJEIFSJSNAIFYFGFENPTRUWTRNYTAFSDHMMJXJQ"

    # CEASAR
    for i in range(len(Helper.ALPHABET)):
        print(Cipher.shift(zasifrovany_text, i))

    RANDOM_ALPHABET = Helper.getRandomPermutation(Helper.ALPHABET)

    # OBECNY ALGORITMUS SUBSTITUCE
    C = "WIRFR WAJUH YFTSD VFSFU UFYA"
    SA = "DKVQFIBJWPESCXHTMYAUOLRGZN"
    M = Cipher.substitute(C, Helper.ALPHABET, SA)
    print(M)

def cv3():
    M = "SLUNECNEATEPLEPOCASICTVRTKEMPROZATIMKONCIVNASLEDUJICICHDVOUDNECHSEZATAHNEVETSINUUZEMIZASAHNEDESTNAHORACHANASEVEROVYCHODEVEVSECHPOLOHACHSNIHOVIKENDUBUDEPOLOJASNOTEPLOTYVNOCIKLESNOUPODNULUPRESDENBUDEMAXIMALNESESTSTUPNU"
    K =  "ZIMA"
    print(Cipher.vigener(M, K, False))


if __name__ == '__main__':
    # cv2()
    #cv02 = Window()
    #cv02.run02()
    cv3()

