from Helper import Helper
from SymmetricCipher import Cipher
from view import Window



def cv2():
    zasifrovany_text = "LTTLQJHMHJSDSNUTRTHNZENAFYJQZRXPTSYWTQTZEIFOJOJONHMMJXQTOJXYJXYFQJGJEUJHSJKNWRFUWTYTUWNUWFANQFXUJHNFQSNITUQSJPITUWTMQNEJHJHMWTRJYJSUTPFEIJPIDEEFIFYJSJPIJSFNSYJWSJYZMJXQTEPTSYWTQZOJEIFSJSNAIFYFGFENPTRUWTRNYTAFSDHMMJXJQ"

    # CEASAR
    for i in range(len(Helper.ALPHABET)):
        print(Cipher.alphabet_shift(zasifrovany_text, i))

    RANDOM_ALPHABET = Helper.get_random_permutation(Helper.ALPHABET)

    # OBECNY ALGORITMUS SUBSTITUCE
    C = "WIRFR WAJUH YFTSD VFSFU UFYA"
    SA = "DKVQFIBJWPESCXHTMYAUOLRGZN"
    M = Cipher.substitute(C, Helper.ALPHABET, SA)
    print(M)

def cv3():
    M = "SLUNECNEATEPLEPOCASICTVRTKEMPROZATIMKONCIVNASLEDUJICICHDVOUDNECHSEZATAHNEVETSINUUZEMIZASAHNEDESTNAHORACHANASEVEROVYCHODEVEVSECHPOLOHACHSNIHOVIKENDUBUDEPOLOJASNOTEPLOTYVNOCIKLESNOUPODNULUPRESDENBUDEMAXIMALNESESTSTUPNU"
    K =  "ZIMA"
    print("Vigener:\n\t"+Cipher.vigener(M, K, decrypt=False))

    #M = "THESIMPLESTPOSSIBLETRANSPOSITIONS"
    #K = "41532"
    M = "RUSKYPREZIDENTVLADIMIRPUTINPRONESLVECTVRTEKTRADICNIPROJEVOSTAVUFEDERACEVENOVALSETOMUZERUSKOMUSIPOKRACOVATVTRANSFORMACIANEMUZESESPOKOJITSESOUCASNYMSTAVEMZMINILSTOUPAJICIPOCETCHUDYCHIZAOSTALOUINFRASTRUKTURUNUTNOUPODPORUDUCHODCUMIMLADYMRODINYMABYSEZVRYTILNEPRIZNIVYDEMOGRAFICKYVYVOJ"
    K = "453216"#PROJEV
    result = Cipher.transposition(M, K)
    print("Col transposition:\n\t"+result["colTransposition"])
    print("Row transposition:\n\t"+result["rowTransposition"])
    #for row in result["matrix"]: print(row)
    print(Helper.get_trans_key_from_word("PROJEV"))


if __name__ == '__main__':
    # cv2()
    #cv02 = Window()
    #cv02.run02()
    cv3()

